sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy

matrix:
  include:
  - python: 2.6
    dist: trusty
  - python: 3.2
    dist: trusty
  - python: 3.3
    dist: trusty

  - python: 3.6
    env:
    - TOXENV=flake8
  - python: 3.6
    env:
    - PUBLISH="true"
    install:
    - pip install coveralls
    - pip install tox-travis
    script:
    - tox
    after_success:
    - coveralls

script:
- python ./test_spec.py

deploy:
  - provider: pypi
    server: https://upload.pypi.org/legacy/
    user: noahmorrison
    password:
      secure: GK+PXWWCczHMQAptgAA6umma0kP+fPsCktHzDnpb4Pa7RZBjxjS1mbRtwSfMm8gWcRYkqjO0la/t3TUP3qjfa+x5JmIwy2YTveBKmSjTxLAb9n7fCWZEGu9GWgGvfsmg2Hhi6NYUp9U7ggtoBXQ4AHgmnPyDCL2TQK32PKj5soM=
    distributions: sdist bdist_wheel
    skip_upload_docs: true
    on:
      tags: true
      repo: noahmorrison/chevron
      branch: master
      condition: $PUBLISH = "true"
  - provider: pypi
    server: https://test.pypi.org/legacy/
    user: noahmorrison
    password:
      secure: GK+PXWWCczHMQAptgAA6umma0kP+fPsCktHzDnpb4Pa7RZBjxjS1mbRtwSfMm8gWcRYkqjO0la/t3TUP3qjfa+x5JmIwy2YTveBKmSjTxLAb9n7fCWZEGu9GWgGvfsmg2Hhi6NYUp9U7ggtoBXQ4AHgmnPyDCL2TQK32PKj5soM=
    distributions: sdist bdist_wheel
    skip_upload_docs: true
    on:
      tags: true
      repo: noahmorrison/chevron
      all_branches: true
      condition: $PUBLISH = "true"
